name: Build and Deploy Angular

on:
  push:
    branches:
      - main  # Rama que dispara el deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      # 4️⃣ Build Angular limpio
      - name: Build Angular app
        working-directory: ./frontend
        run: npx ng build --configuration production

      - name: Ajustar base href
        working-directory: ./frontend
        run: sed -i 's|<base href="/">|<base href="/fabian_site/deploy-frontend/">|' dist/frontend-app/index.html


      # 6️⃣ Limpiar carpeta anterior en el servidor
      - name: Limpiar carpeta de deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: rm -rf /var/www/fabian_site/deploy-frontend/*

      # 7️⃣ Deploy directo al servidor
      - name: Deploy to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/dist/frontend-app/**"
          target: "/var/www/fabian_site/deploy-frontend"
          overwrite: true
          debug: true
